/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Connection.MessageLog;

import java.sql.Timestamp;

/**
 *
 * @author Bernhard
 */
public class LogItem extends javax.swing.JPanel {
    
    /**
     * Creates new form ContactProfile
     */
    public LogItem() {
        initComponents();
    }
    
    public static LogItem getHeader() {
        LogItem li =new LogItem();
        li.lblTimeIn.setText("Time In");
        li.lblTimeOut.setText("Time Out");
        li.lblDelay.setText("Delay");
        li.lblMsgType.setText("Type");
        return li;
    }
    
    public void setStampedMessage(TimeStampedMessage msg) {
        lblTimeIn.setText(msg.timestamp.toString());
        lblTimeOut.setText(msg.msg.getTimestamp());
        lblMsgType.setText(msg.msg.handle().name());
        
        lblDelay.setText(getDelay(Timestamp.valueOf(msg.msg.getTimestamp()), msg.timestamp));
    }
    
    private String getDelay(Timestamp outTime, Timestamp inTime) {
        int years = inTime.getYear() - outTime.getYear();
        int months =inTime.getMonth() - outTime.getMonth();
        int days =inTime.getDay() - outTime.getDay() + (years + months/12) * 365;
        
        int hours =inTime.getHours() - outTime.getHours() + days * 24;
        int minutes =inTime.getMinutes() - outTime.getMinutes() + hours * 60;
        int seconds =inTime.getSeconds() - outTime.getSeconds() + minutes * 60;
        int nano =inTime.getNanos() - outTime.getNanos() + seconds * 1000000000;
        
        seconds =nano / 1000000000;
        nano -=seconds * 1000000000;
        
        return seconds +"." + nano;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimeOut = new javax.swing.JLabel();
        lblTimeIn = new javax.swing.JLabel();
        lblDelay = new javax.swing.JLabel();
        lblMsgType = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgType, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblMsgType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    }//GEN-LAST:event_formMouseReleased

    @Override
    public String toString() {
        String result ="";
        
        result +=lblTimeIn.getText()+",";
        result +=lblTimeOut.getText()+",";
        result +=lblMsgType.getText()+",";
        result +=lblDelay.getText();
        
        return result;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDelay;
    private javax.swing.JLabel lblMsgType;
    private javax.swing.JLabel lblTimeIn;
    private javax.swing.JLabel lblTimeOut;
    // End of variables declaration//GEN-END:variables
}