/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package connection.messageLog;

import java.io.FileNotFoundException;
import java.io.PrintWriter;

/**
 *
 * @author Bernhard
 */
public class MessageLog extends javax.swing.JFrame {

    /**
     * Creates new form MessageLog
     */
    public MessageLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnLogScroll = new javax.swing.JScrollPane();
        lgtLogList = new connection.messageLog.LogList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Message Log");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        spnLogScroll.setViewportView(lgtLogList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnLogScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnLogScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close() {
        formWindowClosing(null);
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        PrintWriter pw = null;
        try {
            pw = new PrintWriter("output"+(new java.util.Date()).getTime()+".csv");
            Object[] list =lgtLogList.list.toArray();
            for (int i=0; i<list.length; i++) {
                LogItem li =(LogItem)list[i];
                pw.println(li);
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } finally {
            pw.close();
        }
    }//GEN-LAST:event_formWindowClosing

    public void add(TimeStampedMessage msg) {
        lgtLogList.addItem(msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private connection.messageLog.LogList lgtLogList;
    private javax.swing.JScrollPane spnLogScroll;
    // End of variables declaration//GEN-END:variables
}
