/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.view.generalUI.contacts;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JPanel;
import mvc.view.generalUI.SeparatorBorder;
import util.Log;

/**
 *
 * @author Bernhard
 */
public class ContactList extends javax.swing.JPanel {
    private GridBagConstraints gbcContactProfile;
    private ArrayList<ContactProfile> list =new ArrayList<ContactProfile>();
    
    /**
     * Creates new form NewJPanel
     */
    public ContactList() {
        initComponents();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.weighty = 1;
        JPanel p =new JPanel();
        p.setBackground(Color.WHITE);
        p.setPreferredSize(new Dimension(0, 0));
        add(p, gbc);
        
        gbcContactProfile = new GridBagConstraints();
        gbcContactProfile.gridwidth = GridBagConstraints.REMAINDER;
        gbcContactProfile.weightx = 1;
        gbcContactProfile.fill = GridBagConstraints.HORIZONTAL;
    }
    
    public ContactProfile getContactProfile(String userID) {
        for (ContactProfile cp: list) {
            if (cp.getUserID().equals(userID)) {
                return cp;
            }
        }
        return null;
    }
    
    public void addProfile(String userID, String fullName, String avatar, int position) {
        ContactProfile contact =new ContactProfile();
        contact.setBorder(new SeparatorBorder(Color.BLACK, false, true, false, true));
        contact.setProfile(userID, fullName, avatar);
        contact.setParent(this);
        list.add(contact);
        add(contact, gbcContactProfile, position);
        update();
        
        Log.write(this.getClass(), "User added");
    }

    public void removeProfile(String userID) {
        ContactProfile profile =getContactProfile(userID);
        if (profile != null) {
            list.remove(profile);
            remove(profile);
            update();
        } else {
            Log.error(this.getClass(), "User to be removed was not found in list");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void update() {
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
