/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.generalUI;

import biz.source_code.base64Coder.Base64Coder;
import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Collection;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import mvc.controller.generalUI.SettingsControl;

/**
 *
 * @author Bernhard
 */
public class Settings extends javax.swing.JFrame implements WindowListener {
    private final static Logger LOGGER = Logger.getLogger(Settings.class.getName());

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        
        addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSettings = new javax.swing.JPanel();
        pnlLeave = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGroupName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        btnLeaveGroup = new javax.swing.JButton();
        pnlSelect = new javax.swing.JPanel();
        btnShowJoin = new javax.swing.JButton();
        btnShowCreate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlJoin = new javax.swing.JPanel();
        cmbGroups = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pwdJoinPassword = new javax.swing.JPasswordField();
        btnJoin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblJoinResponse = new javax.swing.JLabel();
        pnlCreate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pwdCreatePassword = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JButton();
        btnCreateBack = new javax.swing.JButton();
        lblCreateResponse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Settings");

        pnlSettings.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Group Name");

        lblGroupName.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Owner Name");

        lblOwnerName.setText(" ");

        btnLeaveGroup.setText("Leave Group");
        btnLeaveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeaveLayout = new javax.swing.GroupLayout(pnlLeave);
        pnlLeave.setLayout(pnlLeaveLayout);
        pnlLeaveLayout.setHorizontalGroup(
            pnlLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLeaveGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLeaveLayout.createSequentialGroup()
                        .addGroup(pnlLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlLeaveLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLeaveLayout.createSequentialGroup()
                                .addComponent(lblGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                .addGap(104, 104, 104))
                            .addComponent(lblOwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlLeaveLayout.setVerticalGroup(
            pnlLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeaveLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGroupName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOwnerName)
                .addGap(18, 18, 18)
                .addComponent(btnLeaveGroup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSettings.add(pnlLeave, "Leave");

        btnShowJoin.setText("Join");
        btnShowJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowJoinActionPerformed(evt);
            }
        });

        btnShowCreate.setText("Create");
        btnShowCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCreateActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectLayout = new javax.swing.GroupLayout(pnlSelect);
        pnlSelect.setLayout(pnlSelectLayout);
        pnlSelectLayout.setHorizontalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(btnShowJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSelectLayout.setVerticalGroup(
            pnlSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(btnShowJoin)
                .addGap(18, 18, 18)
                .addComponent(btnShowCreate)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pnlSettings.add(pnlSelect, "Select");

        cmbGroups.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "1", "1" }));

        jLabel3.setText("Select Group");

        jLabel5.setText("Password");

        btnJoin.setText("Join");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblJoinResponse.setText(" ");

        javax.swing.GroupLayout pnlJoinLayout = new javax.swing.GroupLayout(pnlJoin);
        pnlJoin.setLayout(pnlJoinLayout);
        pnlJoinLayout.setHorizontalGroup(
            pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJoinLayout.createSequentialGroup()
                .addGroup(pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJoinLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pwdJoinPassword))
                    .addGroup(pnlJoinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJoinLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cmbGroups, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlJoinLayout.createSequentialGroup()
                                .addGroup(pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(0, 447, Short.MAX_VALUE))))
                    .addGroup(pnlJoinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlJoinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlJoinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJoinResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlJoinLayout.setVerticalGroup(
            pnlJoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJoinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdJoinPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJoinResponse)
                .addGap(4, 4, 4)
                .addComponent(btnJoin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pnlSettings.add(pnlJoin, "Join");

        jLabel6.setText("Group Name");

        jLabel7.setText("Group Password");

        btnCreate.setText("Create and Join");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCreateBack.setText("Back");
        btnCreateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBackActionPerformed(evt);
            }
        });

        lblCreateResponse.setText(" ");

        javax.swing.GroupLayout pnlCreateLayout = new javax.swing.GroupLayout(pnlCreate);
        pnlCreate.setLayout(pnlCreateLayout);
        pnlCreateLayout.setHorizontalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtName))
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pwdCreatePassword))
                            .addGroup(pnlCreateLayout.createSequentialGroup()
                                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 430, Short.MAX_VALUE))))
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCreateResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCreateLayout.setVerticalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreateResponse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateBack)
                .addContainerGap())
        );

        pnlSettings.add(pnlCreate, "Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveGroupActionPerformed
        setView(1);
    }//GEN-LAST:event_btnLeaveGroupActionPerformed

    private void btnShowJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowJoinActionPerformed
        setView(2);
    }//GEN-LAST:event_btnShowJoinActionPerformed

    private void btnShowCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCreateActionPerformed
        setView(3);
    }//GEN-LAST:event_btnShowCreateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        SettingsControl.INSTANCE.leave();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        String groupName =(String)cmbGroups.getSelectedItem();
        int selectedIndex =cmbGroups.getSelectedIndex();
        String password =Base64Coder.encodeString(new String(pwdJoinPassword.getPassword()));
        SettingsControl.INSTANCE.joinGroup(groupName, selectedIndex, password);
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setView(1);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBackActionPerformed
        setView(1);
    }//GEN-LAST:event_btnCreateBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String groupName =txtName.getText();
        if (groupName.isEmpty()) {
            lblCreateResponse.setText("Please fill in the group name");
        } else {
            String pwd =Base64Coder.encodeString(new String(pwdCreatePassword.getPassword()));
            SettingsControl.INSTANCE.createGroup(groupName, pwd);
        }
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLeaveGroup;
    private javax.swing.JButton btnShowCreate;
    private javax.swing.JButton btnShowJoin;
    private javax.swing.JComboBox cmbGroups;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCreateResponse;
    private javax.swing.JLabel lblGroupName;
    private javax.swing.JLabel lblJoinResponse;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlJoin;
    private javax.swing.JPanel pnlLeave;
    private javax.swing.JPanel pnlSelect;
    private javax.swing.JPanel pnlSettings;
    private javax.swing.JPasswordField pwdCreatePassword;
    private javax.swing.JPasswordField pwdJoinPassword;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent we) {
    }

    @Override
    public void windowClosing(WindowEvent we) {
    }

    @Override
    public void windowClosed(WindowEvent we) {
        SettingsControl.INSTANCE.initiate(0);
    }

    @Override
    public void windowIconified(WindowEvent we) {
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
    }

    @Override
    public void windowActivated(WindowEvent we) {
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
    }

    public void updateDetails(String groupName, String ownerName, boolean isOwner) {
        lblGroupName.setText(groupName);
        lblOwnerName.setText(ownerName);
    }
    
    public void updateGroupList(Collection<String> groupNames) {
        cmbGroups.setModel(new DefaultComboBoxModel(groupNames.toArray(new String[0])));
    }

    public void setView(int state) {
        CardLayout cl = (CardLayout)(pnlSettings.getLayout());
        switch (state) {
            case 0:
                cl.show(pnlSettings, "Leave");
                break;
            case 1:
                cl.show(pnlSettings, "Select");
                SettingsControl.INSTANCE.requestGroupList();
                break;
            case 2:
                cl.show(pnlSettings, "Join");
                break;
            case 3:
                cl.show(pnlSettings, "Create");
                txtName.setText(SettingsControl.getUserFullname());
                break;
        }
    }

    public void setJoinResponse(String response) {
        lblJoinResponse.setText(response);
    }
    
    public void clear() {
        txtName.setText("");
        cmbGroups.setModel(new DefaultComboBoxModel());
        pwdCreatePassword.setText("");
        pwdJoinPassword.setText("");
        lblGroupName.setText("");
        lblJoinResponse.setText("");
        lblOwnerName.setText("");
        lblCreateResponse.setText("");
    }

    public void setCreateResponse(String response) {
        lblCreateResponse.setText(response);
    }
}
