/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.controller.videoMessages;

/**
 *
 * @author Bernhard
 */
public class VideoPane extends javax.swing.JPanel {
    VideoFrame parent;
    
    /**
     * Creates new form VideoPane
     */
    public VideoPane() {
        initComponents();
    }
    
    public void setImage(String image) {
//        lblVideo.setIcon(ImageUtils.resizeConvert(image, lblVideo.getWidth(), 
//                lblVideo.getHeight()));
        imageContainer1.setImage(image,false);
//        this.paintImmediately(this.getBounds());
    }
    
    public void clear() {
        imageContainer1.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageContainer1 = new mvc.view.generalUI.containers.ImageContainer();

        setPreferredSize(new java.awt.Dimension(909, 399));

        javax.swing.GroupLayout imageContainer1Layout = new javax.swing.GroupLayout(imageContainer1);
        imageContainer1.setLayout(imageContainer1Layout);
        imageContainer1Layout.setHorizontalGroup(
            imageContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
        );
        imageContainer1Layout.setVerticalGroup(
            imageContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mvc.view.generalUI.containers.ImageContainer imageContainer1;
    // End of variables declaration//GEN-END:variables

    void setParent(VideoFrame parent) {
        this.parent =parent;
        (new Thread(new Runnable() {
            @Override
            public void run() {
                while (VideoPane.this.isVisible()) {
                    if (VideoPane.this.parent.hasPicture()) {
                        setImage(VideoPane.this.parent.getPicture());
                    } else {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException e) {
                            
                        }
                    }
                }
            }
        })).start();
    }
}
