/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.controller.videoMessages;

import java.util.ArrayList;

/**
 *
 * @author Bernhard
 */
public class VideoFrame extends javax.swing.JFrame {
    private String streamID;
    private ArrayList<String> imageBuffer;
    
    /**
     * Creates new form VideoFrame
     * @param streamID
     */
    public VideoFrame(String streamID) {
        imageBuffer =new ArrayList<String>();
        this.streamID =streamID;
        initComponents();
        
        videoPane1.setParent(this);
    }

    public String getStreamID() {
        return streamID;
    }
    
    public void write(final String image) {
        imageBuffer.add(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoPane1 = new mvc.controller.videoMessages.VideoPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        videoPane1.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mvc.controller.videoMessages.VideoPane videoPane1;
    // End of variables declaration//GEN-END:variables

    protected boolean hasPicture() {
        return !imageBuffer.isEmpty();
    }

    protected String getPicture() {
        if (hasPicture()) {
            return imageBuffer.remove(0);
        } else {
            return "";
        }
    }
}
