/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.authentication;

import java.awt.Color;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.LineBorder;
import mvc.controller.authentication.RegisterControl;

/**
 *
 * @author Bernhard
 */
public class Register extends javax.swing.JFrame {
    private final static Logger LOGGER = Logger.getLogger(Register.class.getName());

    private boolean valid =true;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    @Override
    public void setVisible(boolean bln) {
        super.setVisible(bln);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();
        pwdRePassword = new javax.swing.JPasswordField();
        lblMessage = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, -1));

        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 269, -1));

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 269, -1));

        txtSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 269, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 269, -1));

        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, -1));

        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 80, -1));

        jLabel8.setText("Re-Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 80, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 390, -1));

        pwdPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pwdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwdPasswordMousePressed(evt);
            }
        });
        pwdPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPasswordFocusLost(evt);
            }
        });
        getContentPane().add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 270, -1));

        pwdRePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pwdRePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdRePasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdRePasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdRePasswordKeyTyped(evt);
            }
        });
        getContentPane().add(pwdRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 270, -1));
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 400, 20));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (!txtUsername.getText().isEmpty()) {
            RegisterControl.checkUsername(txtUsername.getText());
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (!txtEmail.getText().contains("@")) {
            setEmailValid(false, "Invalid email");
        }
        if (!txtEmail.getText().contains(".")) {
            setEmailValid(false, "Invalid email");
        }
        if (!txtEmail.getText().isEmpty()) {
            RegisterControl.checkEmail(txtEmail.getText());
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String username =txtUsername.getText();
        String name =txtName.getText();
        String surname =txtSurname.getText();
        String email =txtEmail.getText();
        String pw =new String(pwdPassword.getPassword());
        valid =true;
        checkFields();
        
        if (valid) {
            txtUsername.setEnabled(false);
            txtName.setEnabled(false);
            txtSurname.setEnabled(false);
            txtEmail.setEnabled(false);
            pwdPassword.setEnabled(false);
            pwdRePassword.setEnabled(false);
            btnRegister.setEnabled(false);
            RegisterControl.register(username, name, surname, email, pw);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void pwdPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPasswordFocusLost
        String pw =new String(pwdPassword.getPassword());
        String pw2 =new String(pwdRePassword.getPassword());
        if (pw2.isEmpty()) {} else {
            if (pw.equals(pw2)) {
                pwdPassword.setBorder(BorderFactory.createLineBorder(Color.GREEN));
                pwdRePassword.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            } else {
                valid =false;
                pwdPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
                pwdRePassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
        }
    }//GEN-LAST:event_pwdPasswordFocusLost

    private void pwdRePasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdRePasswordKeyTyped
        String pw =new String(pwdPassword.getPassword());
        String pw2 =new String(pwdRePassword.getPassword());
        if (pw2.isEmpty()) {} else {
            if (pw.equals(pw2)) {
                pwdPassword.setBorder(BorderFactory.createLineBorder(Color.GREEN));
                pwdRePassword.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            } else {
                valid =false;
                pwdPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
                pwdRePassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
        }
    }//GEN-LAST:event_pwdRePasswordKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        RegisterControl.back();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void pwdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdPasswordMousePressed
        pwdPasswordFocusLost(null);
    }//GEN-LAST:event_pwdPasswordMousePressed

    private void pwdRePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdRePasswordKeyPressed
        pwdRePasswordKeyTyped(evt);
    }//GEN-LAST:event_pwdRePasswordKeyPressed

    private void pwdRePasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdRePasswordKeyReleased
        pwdRePasswordKeyTyped(evt);
    }//GEN-LAST:event_pwdRePasswordKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdRePassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void setUsernameValid(boolean taken, String hint) {
        if (!taken) {
            valid =true;
            txtUsername.setBorder(BorderFactory.createLineBorder(Color.RED)); 
        } else {
            txtUsername.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        }
        txtUsername.setToolTipText(hint);
        txtUsername.invalidate();
    }

    public void setEmailValid(boolean taken, String hint) {
        if (!taken) {
            valid =false;
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED)); 
        } else {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        }
        txtEmail.setToolTipText(hint);
        txtEmail.invalidate();
    }

    private void checkFields() {
        txtUsernameFocusLost(null);
        
        if (txtName.getText().isEmpty()) {
            valid =false;
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else {
            txtName.setBorder(BorderFactory.createLineBorder(new Color(204,204,255)));
        }
        
        if (txtSurname.getText().isEmpty()) {
            valid =false;
            txtSurname.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else {
            txtSurname.setBorder(BorderFactory.createLineBorder(new Color(204,204,255)));
        }
        
        txtEmailFocusLost(null);
        pwdPasswordFocusLost(null);
        pwdRePasswordKeyTyped(null);
    }

    public void setResult(boolean success) {
        if (success) {
            lblMessage.setText("Registration successful.");
        } else {
            lblMessage.setText("Error registering.");
        }
    }
}
