package userInterface.clientGUI.contacts;

import client.Colleague;
import userInterface.clientGUI.GUI;
import Utils.ImageUtils;
import utils.Log;
import utils.MessageFactory;
import Utils.MessageUtils;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mediaStreaming.audio.AudioLine;
import mediaStreaming.audio.AudioStreamer;
import mediaStreaming.video.VideoStreamer;

public class UserProfile extends javax.swing.JPanel {
    private GUI userInterface =null;
    private Colleague user =null;
    
    private VideoStreamer vStream;
    private AudioStreamer aStream;
    
    public UserProfile() {
        initComponents();
        
        streamBtn.setVisible(false);
    }
    
    public void setUserInterface(GUI userInterface) {
        this.userInterface =userInterface;
        vStream =new VideoStreamer(userInterface.getConnection());
        aStream =new AudioStreamer(userInterface.getConnection());
    }
    
    public void setUser(Colleague user) {
        this.user =user;
        vStream.setStream(new Messages.Media.VideoStream(user.getUserID(), 
                Messages.Message.SERVER, MessageUtils.generateStreamID(
                        user.getEmail(), MessageUtils.StreamType.VIDEO)));
        aStream.setStream(new Messages.Media.AudioStream(user.getUserID(), 
                Messages.Message.SERVER, MessageUtils.generateStreamID(
                        user.getEmail(), MessageUtils.StreamType.AUDIO)));
        
        lblUsername.setText(user.getUsername());
        lblEmail.setText(user.getEmail());
        lblID.setText(""+user.getUserID());
        lblAvatar.setImage(user.getAvatar(),true);
    }
    
    public int getUserID() {
        return user.getUserID();
    }
    
    public String getUsername() {
        return user.getUsername();
    }
    
    public void addMessage(Messages.StringMessage sm) {
        user.addMessage(sm);
    }
    
    public void formWindowClosing(java.awt.event.WindowEvent evt) {
        if (evt != null) {
			if (videoBtn.isPressed()) {
                vStream.stop();
            }
            if (audioBtn.isPressed()) {

            }
            if (streamBtn.isPressed()) {

            }
        } else {
            Log.error(this, 
                    "Unknown access to formWindowClosing in UserProfile.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvatar = new userInterface.clientGUI.ImageContainer();
        lblUsername = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        audioBtn = new userInterface.clientGUI.Button();
        videoBtn = new userInterface.clientGUI.Button();
        streamBtn = new userInterface.clientGUI.Button();
        lblID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(208, 192));
        setMinimumSize(new java.awt.Dimension(208, 192));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(208, 192));
        setRequestFocusEnabled(false);

        lblAvatar.setMaximumSize(new java.awt.Dimension(133, 133));
        lblAvatar.setMinimumSize(new java.awt.Dimension(133, 133));
        lblAvatar.setPreferredSize(new java.awt.Dimension(133, 133));
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatarMouseClicked(evt);
            }
        });

        lblUsername.setText("User");
        lblUsername.setToolTipText("");
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsernameMouseClicked(evt);
            }
        });

        lblEmail.setText("Something");

        audioBtn.setBackground(new java.awt.Color(255, 255, 255));
        audioBtn.setBorder(null);
        audioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unclicked-microphone.png"))); // NOI18N
        audioBtn.setBorderPainted(false);
        audioBtn.setContentAreaFilled(false);
        audioBtn.setMaximumSize(new java.awt.Dimension(37, 37));
        audioBtn.setMinimumSize(new java.awt.Dimension(37, 37));
        audioBtn.setPreferredSize(new java.awt.Dimension(37, 37));
        audioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioBtnActionPerformed(evt);
            }
        });
        audioBtn.setUnclicked(new javax.swing.ImageIcon(getClass().getResource("/unclicked-microphone.png")));
        audioBtn.setClicked(new javax.swing.ImageIcon(getClass().getResource("/clicked-microphone.png")));

        videoBtn.setBackground(new java.awt.Color(255, 255, 255));
        videoBtn.setBorder(null);
        videoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unclicked-camera.png"))); // NOI18N
        videoBtn.setBorderPainted(false);
        videoBtn.setContentAreaFilled(false);
        videoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoBtnActionPerformed(evt);
            }
        });
        videoBtn.setUnclicked(new javax.swing.ImageIcon(getClass().getResource("/unclicked-camera.png")));
        videoBtn.setClicked(new javax.swing.ImageIcon(getClass().getResource("/clicked-camera.png")));

        streamBtn.setBackground(new java.awt.Color(255, 255, 255));
        streamBtn.setBorder(null);
        streamBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unclicked-stream.png"))); // NOI18N
        streamBtn.setBorderPainted(false);
        streamBtn.setContentAreaFilled(false);
        streamBtn.setEnabled(false);
        streamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamBtnActionPerformed(evt);
            }
        });
        streamBtn.setUnclicked(new javax.swing.ImageIcon(getClass().getResource("/unclicked-stream.png")));
        streamBtn.setClicked(new javax.swing.ImageIcon(getClass().getResource("/clicked-stream.png")));

        lblID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(audioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(videoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(streamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblID))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(videoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(streamBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(audioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void audioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioBtnActionPerformed
        userInterface.getConnection().writeSafe(
                MessageFactory.generateStreamProperty(user.getUserID(), 
                        Messages.Message.SERVER, aStream.getStreamID(), 
                        !audioBtn.isPressed()));
        
        if (!audioBtn.isPressed()) {
            int selectedUID =userInterface.getContactList().getSelectedUserID();
            if (selectedUID >= 0) {
                userInterface.getConnection().writeSafe(
                        MessageFactory.generateStreamUpdate(user.getUserID(), 
                                Messages.Message.SERVER, aStream.getStreamID(),
                                selectedUID, 1));
                
                userInterface.getContactList().getSelectedProfile().setInAudio(true);
            }
            
            aStream.start();
        } else {
            aStream.stop();
            aStream.setStream(new Messages.Media.AudioStream(user.getUserID(), 
                    Messages.Message.SERVER, MessageUtils.generateStreamID(
                        user.getEmail(), MessageUtils.StreamType.AUDIO)));
        }
        audioBtn.togglePressed();
    }//GEN-LAST:event_audioBtnActionPerformed

    private void videoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoBtnActionPerformed
        userInterface.getConnection().writeSafe(
                MessageFactory.generateStreamProperty(user.getUserID(), 
                        Messages.Message.SERVER, vStream.getStreamID(), 
                        !videoBtn.isPressed()));
        
        if (!videoBtn.isPressed()) {
            int selectedUID =userInterface.getContactList().getSelectedUserID();
            if (selectedUID >= 0) {
                userInterface.getConnection().writeSafe(
                        MessageFactory.generateStreamUpdate(user.getUserID(), 
                                Messages.Message.SERVER, vStream.getStreamID(),
                                selectedUID, 1));
                
                userInterface.getContactList().getSelectedProfile().setInVideo(true);
            }
            
            vStream.start();
        } else {
            vStream.stop();
            vStream.setStream(new Messages.Media.VideoStream(user.getUserID(), 
                    Messages.Message.SERVER, MessageUtils.generateStreamID(
                        user.getEmail(), MessageUtils.StreamType.VIDEO)));
        }
        videoBtn.togglePressed();
    }//GEN-LAST:event_videoBtnActionPerformed

    private void streamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streamBtnActionPerformed
//        Colleague selectedColleague =userInterface.getContactPane().getSelectedColleague();
//        if (selectedColleague != null) {
//            if (streamBtn.isPressed()) {
//                selectedColleague.startAudioStream(MessageUtils.intToArray(userInterface.getContactPane().getSelectedID()));
//                selectedColleague.startVideoStream();
//            } else {
//                selectedColleague.stopAudioStream();
//                selectedColleague.stopVideoStream();
//            }
//        }
//        streamBtn.togglePressed();
    }//GEN-LAST:event_streamBtnActionPerformed

    private void lblAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseClicked
        if (evt.getButton() == 3) {
            try {
                JFileChooser chooser =new JFileChooser();
                chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                chooser.setMultiSelectionEnabled(false);
                FileNameExtensionFilter filter =new FileNameExtensionFilter("images", "png", "jpg", "jpeg", "bmp");
                chooser.setFileFilter(filter);
                
                if (chooser.showOpenDialog(null) == 0) {
                    File cf =chooser.getSelectedFile();

                    setAvatar(ImageIO.read(cf));
                }
            } catch (IOException e) {
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_lblAvatarMouseClicked

    private void lblUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseClicked
        if (evt.getButton() == 3) {
            try {
                String answer =(String)JOptionPane.showInputDialog(this, "Enter new name", "Name change", JOptionPane.QUESTION_MESSAGE, null, null, lblUsername.getText());
                
                if (!answer.equals(user.getUsername())) {
                    userInterface.getConnection().writeSafe(
                            MessageFactory.generateUpdateUsername(
                                    user.getUserID(), answer));
                }
            } catch (ClassCastException cce) {
                Log.error(this, "Cast exception during username retrieval");
            }
        }
    }//GEN-LAST:event_lblUsernameMouseClicked
    
    private void setAvatar(BufferedImage image) {
        lblAvatar.setImage(image, true);
        userInterface.getConnection().writeSafe(
                MessageFactory.generateUpdateAvatar(user.getUserID(), 
                        ImageUtils.encodeToString(image, "png")));
    }
    
    public boolean isAudioStream() {
        return audioBtn.isPressed();
    }
    
    public boolean isVideoStream() {
        return videoBtn.isPressed();
    }
    
    protected String getVideoStreamID() {
        return vStream.getStreamID();
    }
    
    protected String getAudioStreamID() {
        return aStream.getStreamID();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private userInterface.clientGUI.Button audioBtn;
    private userInterface.clientGUI.ImageContainer lblAvatar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblUsername;
    private userInterface.clientGUI.Button streamBtn;
    private userInterface.clientGUI.Button videoBtn;
    // End of variables declaration//GEN-END:variables
}