/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.ClientGUI;

import Utils.ImageUtils;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Bernhard
 */
public class ImageContainer extends javax.swing.JPanel {
    ImageIcon icon;
    
    public ImageContainer() {
        initComponents();
    }
    
    public void setImage(String base64Image) {
        setImage(ImageUtils.decodeToImage(base64Image));
    }
    
    public void setImage(URL filename) throws IOException {
        setImage(ImageIO.read(filename));
    }
    
    public void clear() {
        this.icon =null;
        validate();
        repaint();
    }

    public void setImage(BufferedImage bi) {
        int width =getPreferredSize().width;
        int height =getPreferredSize().height;
        
        if (width != 0 && height != 0) {
            this.icon =ImageUtils.resizeConvert(bi, new java.awt.Dimension(width,height));
//            this.icon =ImageUtils.resizeConvert(base64Image, this.getSize());
        }
        
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if (icon != null) {
            g.drawImage(icon.getImage(), (this.getWidth()-icon.getIconWidth())/2, 
                    (this.getHeight()-icon.getIconHeight())/2, icon.getImageObserver());
        }
    }
}
