/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.ClientGUI.Contacts;

import Client.Colleague;
import Utils.ImageUtils;
import Utils.Log;
import Utils.MessageFactory;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Bernhard
 */
public class ContactProfile extends javax.swing.JPanel {
    private Colleague owner;
    private boolean selected =false;
    private ContactList parent;
    
    private boolean acceptedVideo =false;
    private boolean acceptedAudio =false;
    private boolean acceptedStream =false;
    
    private String videoStreamID;
    private String audioStreamID;
    private String streamStreamID;

    /**
     * Creates new form ContactProfile
     */
    public ContactProfile() {
        initComponents();
        
    }
    
    public void setColleague(Colleague owner) {
        this.owner =owner;
        lblName.setText(owner.getUsername());
        lblEmail.setText(owner.getEmail());
        lblID.setText(""+owner.getUserID());
        
        lblAvatar.setIcon(ImageUtils.resizeConvert(owner.getAvatar(), 50, 50));
    }
    
    public void setContactList(ContactList list) {
        this.parent =list;
    }
    
    public int getUserID() {
        return owner.getUserID();
    }
    
    public String getUsername() {
        return owner.getUsername();
    }
    
    public void setUsername(String username) {
        owner.setUsername(username);
    }
    
    public void updateAvatar(String image) {
        lblAvatar.setIcon(ImageUtils.resizeConvert(image, 50, 50));
    }
    
    public void addMessage(Messages.StringMessage sm) {
        owner.addMessage(sm);
    }
    
    public ArrayList<Messages.StringMessage> getMessageHistory() {
        return owner.getMessageHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        videoBtn = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblName.setText("Name");

        jButton12.setBackground(new java.awt.Color(255, 0, 0));

        videoBtn.setBackground(new java.awt.Color(51, 255, 0));
        videoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoBtnActionPerformed(evt);
            }
        });

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_profile.png"))); // NOI18N

        lblEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(videoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblID))
                            .addComponent(lblEmail))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblName)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(videoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblID))))
            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!selected) {
            parent.select(this);
        } else {
            parent.unselect(this);
        }
        
    }//GEN-LAST:event_formMouseClicked

    private void videoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoBtnActionPerformed
        if (acceptedVideo) {
            parent.getUserInterface().getConnection().writeSafe(
                    MessageFactory.generateStreamResponse(
                            parent.getUserInterface().getUserID(), 
                            videoStreamID, true));
            acceptedVideo =false;
        } else {
            parent.getUserInterface().getConnection().writeSafe(
                    MessageFactory.generateStreamResponse(
                            parent.getUserInterface().getUserID(), 
                            videoStreamID, false));
            acceptedVideo =true;
        }
    }//GEN-LAST:event_videoBtnActionPerformed

    protected void select() {
        setBackground(new Color(0, 0, 158));
        setForeground(Color.WHITE);
        selected =true;
        
//        Log.write(this,"Selected Person: "+owner.getUsername()+" - "+owner.getUserID());
    }
    
    protected void unselect() {
        setBackground(Color.WHITE);
        setForeground(Color.BLACK);
        selected =false;
        
//        Log.write(this,"Unselected Person: "+owner.getUsername());
    }
    
    public void incomingVideo(boolean incoming, String streamID) {
        videoStreamID =streamID;
//        videoBtn.setVisible(incoming);
        
        videoBtnActionPerformed(null); //auto accept
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton videoBtn;
    // End of variables declaration//GEN-END:variables
}