/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.generalUI.videoMessages;

/**
 *
 * @author Bernhard
 */
public class VideoPane extends javax.swing.JPanel {
    VideoFrame parent;
    
    /**
     * Creates new form VideoPane
     */
    public VideoPane() {
        initComponents();
    }
    
    public void setImage(String image) {
//        lblVideo.setIcon(ImageUtils.resizeConvert(image, lblVideo.getWidth(), 
//                lblVideo.getHeight()));
        lblVideo.setImage(image,false);
//        this.paintImmediately(this.getBounds());
    }
    
    public void clear() {
        lblVideo.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVideo = new userInterface.generalUI.ImageContainer();

        setPreferredSize(new java.awt.Dimension(909, 399));

        javax.swing.GroupLayout lblVideoLayout = new javax.swing.GroupLayout(lblVideo);
        lblVideo.setLayout(lblVideoLayout);
        lblVideoLayout.setHorizontalGroup(
            lblVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        lblVideoLayout.setVerticalGroup(
            lblVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private userInterface.generalUI.ImageContainer lblVideo;
    // End of variables declaration//GEN-END:variables

    void setParent(VideoFrame parent) {
        this.parent =parent;
        (new Thread(new Runnable() {
            @Override
            public void run() {
                while (VideoPane.this.isVisible()) {
                    if (VideoPane.this.parent.hasPicture()) {
                        setImage(VideoPane.this.parent.getPicture());
                    } else {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException e) {
                            
                        }
                    }
                }
            }
        })).start();
    }
}
