/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.view.generalUI.message;

import java.awt.Color;
import java.awt.Rectangle;
import javax.swing.JPanel;
import mvc.view.generalUI.SeparatorBorder;

/**
 *
 * @author Bernhard
 */
public class msgItem extends JPanel {
//    private boolean multiperson =false;
//    private int userID =-1;

    /**
     * Creates new form MessageItem
     */
    public msgItem() {
        initComponents();
        setBorder(new SeparatorBorder(Color.BLACK, true, true, true, true));
    }
    
    public void setContent(String name, String time, String message) {
        lblName.setText(name);
        lblTime.setText(time);
        
        txaMessageArea.setText(message);
        Rectangle r =txaMessageArea.getBounds();
        txaMessageArea.setBounds(r.x, r.y, r.width, txaMessageArea.getPreferredSize().height);
    }
    
//    public void setMultiperson(boolean multiperson) {
//        this.multiperson =multiperson;
//    }

//    public void setUserID(int userID) {
//        this.userID = userID;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMessageArea = new javax.swing.JTextArea();
        lblTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblName.setText("Name");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txaMessageArea.setEditable(false);
        txaMessageArea.setColumns(1);
        txaMessageArea.setRows(1);
        txaMessageArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaMessageArea);

        lblTime.setText("TIME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextArea txaMessageArea;
    // End of variables declaration//GEN-END:variables
}
